# Generated by Django 3.2.5 on 2022-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsInfo',
            fields=[
                ('txid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
